
import './globals.css'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Tasfia'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className=''>
        {children}
      </body>
    </html>
  )
}
